services:
  steam:
    image: steam
    container_name: steam
    privileged: true # nodig voor GPIO toegang
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 5000:5000 # Flask
    devices:
      - /dev/gpiomem:/dev/gpiomem # GPIO toegang
    restart: unless-stopped

  neopixel:
    image: neopixel
    container_name: neopixel
    privileged: true # nodig voor GPIO toegang
    devices:
      - /dev/gpiomem:/dev/gpiomem # GPIO toegang
    restart: unless-stopped
<<<<<<< HEAD
#    networks:
#        - steam_network
=======
>>>>>>> refs/remotes/origin/prod_webserv

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@albertove.nl
      - PGADMIN_DEFAULT_PASSWORD=Steam123!


volumes:
  postgres_data:
