services:
  steam:
    image: steam
    container_name: steam
    privileged: true # nodig voor GPIO toegang
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 5000:5000 # Flask
    devices:
      - /dev/gpiomem:/dev/gpiomem # GPIO toegang
    restart: unless-stopped

  neopixel:
    image: neopixel
    container_name: neopixel
    privileged: true # nodig voor GPIO toegang
    devices:
      - /dev/gpiomem:/dev/gpiomem # GPIO toegang
    restart: unless-stopped
#    networks:
#        - steam_network

#  postgres:
#    image: postgres
#    container_name: postgres
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    restart: unless-stopped
#    networks:
#      - steam_network

#networks:
#    default:
#        external: true
#        name: steam_network