services:
  steam:
    image: steam
    container_name: steam
    privileged: true # Required for GPIO access
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
    devices:
      - /dev/gpiomem:/dev/gpiomem # GPIO access
    restart: unless-stopped
    networks:
        - steam_network

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    networks:
      - steam_network

networks:
    default:
        external: true
        name: steam_network