services:
  steam:
    image: steam
    container_name: steam
    privileged: true # Required for GPIO access
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
    devices:
      - /dev/gpiomem:/dev/gpiomem # GPIO access
    restart: unless-stopped